name: UI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install playwright pytest-playwright pytest-asyncio pytest-html pytest-cov
    
    - name: Install Playwright browsers
      run: |
        playwright install --with-deps ${{ matrix.browser }}
    
    - name: Start backend server
      run: |
        cd backend
        uvicorn app:app --host 0.0.0.0 --port 8080 &
        sleep 10  # Wait for server to start
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Wait for server to be ready
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:8080/health; then
            echo "Server is ready"
            break
          fi
          echo "Waiting for server... ($i/30)"
          sleep 2
        done
    
    - name: Run UI tests
      run: |
        python -m pytest tests/ui/ \
          --browser=${{ matrix.browser }} \
          --headed=false \
          --html=test-report-${{ matrix.browser }}.html \
          --self-contained-html \
          --cov=backend \
          --cov-report=xml \
          -v
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          test-report-${{ matrix.browser }}.html
          tests/ui/screenshots/
          coverage.xml
    
    - name: Upload coverage to Codecov
      if: matrix.browser == 'chromium'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: uitests
        name: codecov-umbrella

  lighthouse:
    runs-on: ubuntu-latest
    needs: ui-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Start backend server
      run: |
        cd backend
        uvicorn app:app --host 0.0.0.0 --port 8080 &
        sleep 10
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Audit URLs using Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        urls: |
          file://${{ github.workspace }}/frontend/index.html
        configPath: ./.lighthouserc.json
        uploadArtifacts: true
        temporaryPublicStorage: true
